### ISSUE TITLE
Homepage not loading `TypeError: Cannot read properties of undefined (reading 'defaultText')`

### ISSUE THREAD

**Issue by jennjunod** [Bedrock-Layouts/Bedrock#2098]
**Describe the bug**

`Cannot read properties of undefined (reading 'defaultText')
TypeError: Cannot read properties of undefined (reading 'defaultText')
    at $.div.theme (https://www.bedrock-layout.dev/assets/index-8b4345ec.js:408:5503)
    at Kr (https://www.bedrock-layout.dev/assets/index-8b4345ec.js:360:2114)
    at dr (https://www.bedrock-layout.dev/assets/index-8b4345ec.js:365:947)
    at https://www.bedrock-layout.dev/assets/index-8b4345ec.js:369:734
    at https://www.bedrock-layout.dev/assets/index-8b4345ec.js:365:1727
    at Gl (https://www.bedrock-layout.dev/assets/doctrine-f3ba5fd0.js:22:19474)
    at oo (https://www.bedrock-layout.dev/assets/doctrine-f3ba5fd0.js:24:1571)
    at J0 (https://www.bedrock-layout.dev/assets/doctrine-f3ba5fd0.js:24:45800)
    at Y0 (https://www.bedrock-layout.dev/assets/doctrine-f3ba5fd0.js:24:39613)
    at m1 (https://www.bedrock-layout.dev/assets/doctrine-f3ba5fd0.js:24:39541)`

**To Reproduce**

When going to https://www.bedrock-layout.dev/?path=/docs/overview-bedrock-layout-primitives--docs the flashes and loads blank. After going to `contributing` then back to `overview-bedrock-layout-primitives--docs` able to see the error listed above. 

**Expected behavior**
See the homepage or be redirected to a different page

**Screenshots**

<img width="1728" alt="image" src="https://github.com/Bedrock-Layouts/Bedrock/assets/77285384/6e236dd5-1155-48f3-8a59-78783e3320c6">
<img width="1728" alt="image" src="https://github.com/Bedrock-Layouts/Bedrock/assets/77285384/b160534a-f215-4a8f-9416-d1af491e87ee">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome and Safari

**Smartphone (please complete the following information):**
 - Device: iPhone 14 pro max
 - OS: 16.6.1
 - Browser Safari

**Additional context**

**Comment by Jarvis1010** [comment]
Looking now....Thanks

**Comment by Jarvis1010** [comment]
Fixed Thank you @jennjunod
